language: english
storage: memory
crawler:
  docpath: test
  docs: [html, htm]
  exceptions: _dab
  tags:
    h1: 20
    h2: 15
    h3: 11
    h4: 9
    h5: 8
    h6: 7
    strong: 7
    b: 7
    em: 5
    i: 5
    dt: 9
    u: 3
    a: 6
logger:
  file: STDOUT
  level: info
search_generator:
  search_data_file: out/search_data.js
  output_encoding: uft-8
  template: base